name: Terraform plan on PR
run-name: Terraform plan
# test CI
on:
    pull_request:
        branches:
            - main
        paths: # Run seulement si ces fichiers sources diffèret des fichiers cibles
            - "terraform/prod/**"
            - ".github/workflows/plan-on-pr.yaml"
permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./terraform/prod/
            shell: bash
        env:
            ARM_USE_OIDC: "true"
            ARM_USE_AZUREAD: "true"
            ARM_CLIENT_ID: ${{ secrets.AZURE_PLAN_CLIENT_PLAN_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        steps:
            - uses: actions/checkout@v6
            
            - uses: hashicorp/setup-terraform@v4

            - name: Terraform fmt
              id: fmt
              run: terraform fmt 
              
            - name: Terraform init
              id: init
              run: terraform init -input=false

            - name: Terraform validate
              id: validate
              run: terraform validate -no-color
              
            - name: Terraform plan
              id: plan
              run: terraform plan -input=false -no-color -lock-timeout=5m