name: Create PR Dev -> Main
run-name: Push to Dev 


permissions:
  contents: read

on:
    workflow_call:
        secrets:
            PR_AUTOMATION_APP_PRIVATE_KEY:
                required: true

jobs:
    create-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Generate token
              id: generate-token
              uses: actions/create-github-app-token@v3
              with:
                client-id: ${{ vars.PR_AUTOMATION_APP_ID}}
                private-key: ${{secrets.PR_AUTOMATION_APP_PRIVATE_KEY}}
            - name: Use API
              run: |
               OPENEND_PR=$(gh pr list --head dev --repo "$GITHUB_REPOSITORY" --base main --state open --json number --jq 'length')
               if [ "$OPENEND_PR" -eq 0 ]; then
                gh pr create --head dev --base main --repo "$GITHUB_REPOSITORY" --title "New PR" --body "$COMMIT_MESSAGE"
               fi

              env: 
                GH_TOKEN: ${{steps.generate-token.outputs.token}}
                COMMIT_MESSAGE: ${{ github.event.head_commit.message }}